# Generated by Django 5.0.7 on 2024-10-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.TextField()),
                ('numberOfParticipants', models.IntegerField()),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('imageUrl', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invitations', models.IntegerField(default=0)),
                ('total_rsvps', models.IntegerField(default=0)),
                ('total_accepted_rsvps', models.IntegerField(default=0)),
                ('total_rejected_rsvps', models.IntegerField(default=0)),
                ('invitaion_accepted_rsvps', models.IntegerField(default=0)),
                ('invitation_rejected_rsvps', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=True)),
            ],
        ),
    ]
